// React/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [userMessage, setUserMessage] = useState('');
  const [displayText, setDisplayText] = useState('Hello World');

  const displayMessage = () => {
    setDisplayText(userMessage || 'Hello World');
  };

  return (
    <div>
      <label htmlFor="messageInput">Message to Display</label>
      <input
        id="messageInput"
        value={userMessage}
        onChange={(e) => setUserMessage(e.target.value)}
        placeholder="Enter your message"
      />
      <button onClick={displayMessage}>Display Message</button>
      <h2>{displayText}</h2>
    </div>
  );
}

export default App;

// Angular/src/app/Angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: 'Angular/src/app/Angular/src/app/app.component.html',
  styleUrls: ['Angular/src/app/Angular/src/app/app.component.ts']
})
export class AppComponent {
  userMessage = '';
  displayText = 'Hello World';

  displayMessage() {
    this.displayText = this.userMessage || 'Hello World';
  }
}

<div>
  <label for="messageInput">Message to Display</label>
  <input id="messageInput" [(ngModel)]="userMessage" placeholder="Enter your message" />
  <button (click)="displayMessage()">Display Message</button>
  <h2>{{ displayText }}</h2>
</div>
